version: "3"
services:

    orientdb:
        image: orientdb:latest
        volumes:
            - orientdb_config:/orientdb/config
            - orientdb_databases:/orientdb/databases
        environment:
            ORIENTDB_ROOT_PASSWORD: root
            ORIENTDB_NODE_NAME: root
        ports:
            - "2480:2480"
            - "2424:2424"
            - "8182:8182"
        networks:
            microservices:
                aliases:
                    - database-orientdb

    accounts:
        build: ./services/accounts
        expose:
            - "3204"
        depends_on:
            - "orientdb"
        networks:
            microservices:
                aliases:
                    - service-accounts

    reviews:
        build: ./services/reviews
        expose:
            - "3203"
        depends_on:
            - "orientdb"
        networks:
            microservices:
                aliases:
                    - service-reviews

    products:
        build: ./services/products
        expose:
            - "3202"
        depends_on:
            - "orientdb"
        networks:
            microservices:
                aliases:
                    - service-products

    inventory:
        build: ./services/inventory
        expose:
            - "3201"
        depends_on:
            - "orientdb"
        networks:
            microservices:
                aliases:
                    - service-inventory

    api-gateway:
        build: ./services/api-gateway
        ports:
            - "3200:3200"
        environment: 
            WAIT_HOSTS: inventory:3201, products:3202, reviews:3203, accounts:3204
        depends_on:
            - "orientdb"
            - "accounts"
            - "reviews"
            - "products"
            - "inventory"
        networks:
            microservices:
                aliases:
                    - service-api-gateway

    webapp:
        build: ./services/webapp
        ports:
            - "3000:3000"
        environment: 
            WAIT_HOSTS: api-gateway:3200
        depends_on:
            - "api-gateway"
        networks:
            microservices:
                aliases:
                    - service-webapp

networks:
    microservices:

volumes:
    orientdb_config:
        driver_opts:
            type: none
            device: ${PWD}/dockerfiles/orientdb/config
            o: bind
    orientdb_databases:
        driver_opts:
            type: none
            device: ${PWD}/dockerfiles/orientdb/databases
            o: bind
